# Schedule for the secret sync cronjob to run
cron_schedule: "*/10 * * * *"

# Address of the vault instance to connect to
vault_address: https://vault.pennlabs.org

# Which namespaces to sync secrets to
namespaces:
  - default

# Name of the cluster within vault
cluster: production

# Options for the vault container
vault:
  image: vault
  tag: "1.6.1"

# Options for the synchronizer container
synchronizer:
  image: postfinance/vault-kubernetes-synchronizer
  tag: "0.1.3"

# Secret-Sync Role ARN to assume
role_arn: change_me
