{{- $values := .Values }}
{{- range .Values.namespaces }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-sync
  namespace: {{ . }}
spec:
  schedule: {{ $values.cron_schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 65534
          serviceAccountName: secret-sync
          volumes:
            - name: vault-token
              emptyDir:
                medium: Memory
          restartPolicy: Never
          initContainers:
            - name: vault-authenticator
              image: "{{ $values.vault.image }}:{{ $values.vault.tag }}"
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args: ["vault login -method=aws -token-only > /home/vault/.vault-token"]
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault/
              env:
                - name: VAULT_ADDR
                  value: {{ $values.vault_address }}
                - name: VAULT_TOKEN_PATH
                  value: /home/vault/.vault-token
          containers:
            - name: vault-kubernetes-synchronizer
              image: "{{ $values.synchronizer.image }}:{{ $values.synchronizer.tag }}"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault/
              env:
                - name: VAULT_ADDR
                  value: {{ $values.vault_address }}
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_TOKEN_PATH
                  value: /home/vault/.vault-token
                - name: SECRET_PREFIX
                  value: ""
                - name: VAULT_SECRETS
                  value: "secrets/{{ $values.cluster }}/{{ . }}/"
{{ end }}
