{{- $values := .Values }}
{{- range .Values.namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync
  namespace: {{ . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $values.role_arn | quote }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secret-sync-role
  namespace: {{ . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secret-sync-rolebinding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: secret-sync
    namespace: {{ . }}
roleRef:
  kind: Role
  name: vault-secret-sync-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secret-sync-crb-{{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-secret-sync
    namespace: {{ . }}
{{ end }}
